---
- name: Install sdk
  shell: curl -s "https://beta.sdkman.io" | bash

- name: Install Java
  shell: /bin/bash -c "source ~/.sdkman/bin/sdkman-init.sh && sdk install java"

- name: Install Maven
  shell: /bin/bash -c "source ~/.sdkman/bin/sdkman-init.sh && sdk install maven"
