---
- hosts: localhost
  become: yes

  pre_tasks:
    - name: Update dnf
      dnf:
        update_cache: true
        state: latest

  roles:
    - role: core
    - role: devtools
    - role: tools
