---
- hosts: localhost
  become: yes

  # TODO: Ajouter les tags pour le faire que sur une install complete (install, core)
  pre_tasks:
    - name: Update dnf
      dnf:
        update_cache: true
        state: latest

  roles:
    - role: core
    - role: devtools
    - role: tools
