---
- name: Add max_parallel_downloads=10 if not present
  lineinfile:
    state: present
    path: /etc/dnf/dnf.conf
    search_string: "max_parallel_downloads"
    line: "max_parallel_downloads=10"
    insertafter: "EOF"

- name: Add fastestmirror=True if not present
  lineinfile:
    state: present
    path: /etc/dnf/dnf.conf
    search_string: "fastestmirror"
    line: "fastestmirror=True"
    insertafter: "EOF"

- name: Add countme=False if not present
  lineinfile:
    state: present
    path: /etc/dnf/dnf.conf
    search_string: "countme"
    line: "countme=False"
    insertafter: "EOF"

- name: Add defaultyes=True if not present
  lineinfile:
    state: present
    path: /etc/dnf/dnf.conf
    search_string: "defaultyes"
    line: "defaultyes=True"
    insertafter: "EOF"
