---
- name: Create font directory
  file:
    path: "{{ ansible_env.HOME }}/.fonts"
    state: directory

- name: Download fonts
  get_url:
    url: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.fonts"
  loop: "{{ fonts }}"

- name: Find archive files
  find:
    paths: "{{ ansible_env.HOME }}/.fonts"
    use_regex: true
    patterns: ['.*\.zip$']
  register: archives

- name: Extract fonts
  unarchive:
    src: "{{ item.path }}"
    dest: "{{ ansible_env.HOME }}/.fonts"
  loop: "{{ archives.files }}"

- name: Remove fonts archive files
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ archives.files }}"
