---
- name: Set GRUB_TIMEOUT to one second
  lineinfile:
    state: present
    path: /etc/default/grub
    search_string: "GRUB_TIMEOUT"
    line: "GRUB_TIMEOUT=1"
    insertafter: "EOF"
  register: grub

- name: Persist changes
  shell: grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg
  when: grub.changed
