---
- name: Install zsh
  dnf:
    name:
      - zsh
      - util-linux-user
    state: latest

- name: Get zsh path
  shell: which zsh
  register: path

- name: Change shell
  user:
    name: "{{ username }}"
    shell: "{{ path.stdout }}"

- name: Download antigen file
  shell: curl -L git.io/antigen > antigen.zsh
  args:
    chdir: "/home/{{ username }}"
    creates: antigen.zsh
  become_user: "{{ username }}"

- name: Execute antigen file
  shell: "zsh /home/{{ username }}/antigen.zsh"
  become_user: "{{ username }}"

- name: Move antigen file
  shell: mv antigen.zsh .antigen/antigen.zsh
  args:
    chdir: "/home/{{ username }}"
  become_user: "{{ username }}"
