---
- name: Install codecs
  dnf:
    name:
      - gstreamer1-plugins-base
      - gstreamer1-plugins-good
      - gstreamer1-plugins-bad-free
      - gstreamer1-plugins-good-extras
      - gstreamer1-plugins-bad-free-extras
      - gstreamer1-plugins-ugly-free
      - gstreamer1-libav
      - gstreamer1-plugins-bad-freeworld
      - gstreamer1-plugins-ugly
      - libdvdcss
    state: present
