---
- name: Enable lazygit repository
  shell: dnf copr enable atim/lazygit -y

- name: Add docker repository
  shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
