---
- name: Clone pfetch git repository
  git:
    repo: "https://github.com/dylanaraps/pfetch"
    dest: "/home/{{ username }}/pfetch"

- name: Install pfetch
  make:
    chdir: "/home/{{ username }}/pfetch"
    target: install

- name: Delete pfetch git repository
  file:
    path: "/home/{{ username }}/pfetch"
    state: absent
