---
- name: Clone pfetch git repository
  git:
    repo: "https://github.com/dylanaraps/pfetch"
    dest: "{{ ansible_env.HOME }}/pfetch"

- name: Install pfetch
  make:
    chdir: "{{ ansible_env.HOME }}/pfetch"
    target: install

- name: Delete pfetch git repository
  file:
    path: "{{ ansible_env.HOME }}/pfetch"
    state: absent
