---
- name: Install fedora softwares
  dnf:
    name: "{{ softwares }}"
    state: latest

- name: Install flatpak softwares
  flatpak:
    name: "{{ flatpakApps }}"
    state: present
  become_user: "{{ username }}"
